title: Steve Swift Pty Ltd
email: steve@steveswift.com.au
description: >-
  Award-winning airworthiness consulting, training and expert witness services
baseurl: ""
url: "https://steveswift.com.au"
permalink: pretty
future: true
copyright: "Â© 2023 Steve Swift Pty Ltd"
# logo: assets/images/logo.png

# metadata for news items - can be overridden as necessary
author:
  name: Steve Swift
  picture: /assets/images/steve-swift-headshot.jpg

linkedin_username: steve-swift-41ab5a42

# Build settings
markdown: kramdown

exclude:
  - migration/

# frontmatter defaults
defaults:
  - scope:
      path: "_people"
    values:
      layout: post

collections:
  people:
    output: true
    permalink: /:collection/:path/
